name: "Build Library"

on:
  push:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    concurrency:
      group: "NPM Release"

    defaults:
      run:
        shell: "bash"

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup"
        uses: "actions/setup-node@v4"
        with:
          always-auth: "TRUE"
          cache: "npm"
          cache-dependency-path: "package-lock.json"
          node-version: "lts/*"

      - name: "Restore"
        run: "npm install"

      - name: "Build"
        run: "npm run build"

      - name: "Upload Distribution"
        uses: "actions/upload-artifact@v4"
        with:
          name: "built-package"
          path: "./dist"
          retention-days: 2

      - name: "Test"
        run: "npm test"
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

      - name: "Release"
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: "npx semantic-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
